#!/bin/sh

# Bookmarks
alias repo='cd /home/ethan/Programming/repo'
alias down='cd /home/ethan/Downloads'
alias golang='cd /home/ethan/Programming/golang'

# Stuff
alias comp='sudo make clean install'

# Get rid of wget-hsts
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

# Set mirrors

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Colorize output 
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='exa -l --icons'
alias lsa='exa -al --icons --no-filesize'

# Change emacs theme 
alias light='ihsec set light'
alias dark='ihsec set dark'
