#!/bin/sh

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Colorize output 
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ls='exa -l --icons'
alias lsa='exa -al --icons --no-filesize'

# xclip copy
alias copy='xclip -sel c <'

# Soft 
# Get rid of wget-hsts
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
# sudo make clean install
alias comp='sudo make clean install'

alias addalias='nvim +200 ~/.config/zsh/zsh-aliases'
